### ISSUE TITLE
E1: Information gathering and Data collection

### ISSUE THREAD

**Issue by Shiimymy** [Shiimymy/Prediction-heritage-housing#1]
**Acceptance Criteria**:
We got all information and collect the data  from the client.

**Tasks**:
- [x] Understand the business requirement as per client need.
- [x] Create a DataCollection Notebook
- [x] Collect the data from Kaggle and save it.
