### ISSUE TITLE
E3: Data Preparation

### ISSUE THREAD

**Issue by Shiimymy** [Shiimymy/Prediction-heritage-housing#3]
**Acceptance Criteria**:
Create the DataCleaning notbook

**Tasks**:
- [x] Do a correlation and PSS Analysis
- [x] Check for missing values
- [x] Clean the data from findings
- [x]  feature engineering
