### ISSUE TITLE
E4:  Modelling and Evaluation

### ISSUE THREAD

**Issue by Shiimymy** [Shiimymy/Prediction-heritage-housing#4]
**Acceptance Criteria**:
Create a predictive model by using different algorithms and hyperparamters to have the best performances.

**Tasks**:
- [x] Find the best algorithms
- [x] Find the best hyperparmters (hyperparameter optimization)
- [x] evaluate the R2 score as well as the plot Actual vs Prediction for both train and test sets
- [x] Evaluate with Jupyter Notebook, if  the ML Pipeline/Model meets the project requirements in the ML Business Case
