### ISSUE TITLE
E5: Dashboard

### ISSUE THREAD

**Issue by Shiimymy** [Shiimymy/Prediction-heritage-housing#5]
**Acceptance Criteria**:
Create a dashboard that the customer required.

**Tasks**:
- [x] Plan the dashboard
- [x] Design the dashboard with a navigation menu
- [x] Use Streamlit  version 0.85.0. for developing the dashboard
- [x] Implement 4 plots in the dashboard with textual interpretation
- [x] Write clear statements on the dashboard to inform the user of the ML model/pipeline performances
