### ISSUE TITLE
E6: Deployment

### ISSUE THREAD

**Issue by Shiimymy** [Shiimymy/Prediction-heritage-housing#6]
**Acceptance Criteria**:
Deploy the Dashboard for the customer to use the app.

**Tasks**:
- [x] Check if README as all criteria
- [x] Maintain Procfile, requirements.txt, runtime.txt, and setup.sh to enable the deployment at Heroku.
- [x] Implement a dashboard using Streamlit version 0.85.0.
